export const SET_TWEETS = "SET_TWEETS";
export const ADD_TWEET = "ADD_TWEET";
export const REMOVE_TWEET = "REMOVE_TWEET";
export const TOGGLE_STAR_TWEET = "TOGGLE_STAR_TWEET";
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const TOGGLE_TOPBAR = "TOGGLE_TOPBAR";
